name: LendingClub.com
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - ipython
  - black
  - keras
  - xgboost
  - pip:
    - tensorflow-macos
    - tensorflow-metal

